# Generated by Django 5.1.5 on 2025-02-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timetable_date", models.DateField()),
                ("timetable_colour", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="UserAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected", models.BooleanField()),
                (
                    "timetable_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="get_availability.timetable",
                    ),
                ),
            ],
        ),
    ]
