# Generated by Django 5.1.5 on 2025-01-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("get_availability", "0001_initial"),
        ("get_availability", "0002_user_alter_useravailability_user"),
        (
            "get_availability",
            "0003_rename_timetable_date_useravailability_timetable_id_and_more",
        ),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timetable_date", models.DateField()),
                ("timetable_colour", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="UserAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="get_availability.user",
                    ),
                ),
                ("selected", models.BooleanField()),
                (
                    "timetable_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="get_availability.timetable",
                    ),
                ),
            ],
        ),
    ]
